[MSVC] fix compiling: added definition of NOMINMAX ( please refer http://www.devx.com/tips/Tip/14540 ) (pipeline.h from libary use std::min|max) for pipeline.cpp added 'f' to float constants ( please refer error C2398: conversion from 'double' to 'const float' requires a narrowing conversion ).